def mainDir="Part2_Docker/Chapter02/2-jenkins-docker"

pipeline {
    agent any

    enviroment{
        docker_hub_credentals = credentials('docker-hub-credentials')
        docker_image_name = 'eun98com/jib-test'
        docker_image_tag = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Pull Codes from Github'){
            steps{
                checkout scm
            }
        }
        stage('Build Codes by Gradle') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew clean build
                """
            }
        }
        stage('Build Docker Image by Jib & Push to Docker-hub Repository') {
            steps {
                    script {
                    def jibArgs = [
                        'to' : [
                            'imgae': "${docker_imagename}:${docker_image_tag}",
                            'auth' : docker_hub_credentals
                            ]
                    ]
                    sh """
                        cd ${mainDir}
                        ./gradlew jib -Djib.to.image=${docker_image_name}:${docker_image_tag} -Djib.console='plain'
                    """
                }
            }
        }
        stage('Deploy to AWS EC2 VM'){
            steps{
                sshagent(credentials : ["deploy-nuc"]) {
                    sh "ssh -o StrictHostKeyChecking=no nuc@10.32.239.42 \
                      docker run -d -p 80:8080 -t ${ecrUrl}/${repository}:${currentBuild.number};'"
                }
            }
        }
    }
}
